---
title: "LinePlot"
author: "wangshuguang"
date: "2025-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggsci)
library(dplyr)
library(stringr)
library(ggplot2)
library(cowplot)
library(reshape2)
library(lubridate)


# pair_scalability_time.csv
## data clean
df <- read.csv("/home/wsg/BM/assess/BMMC/scalability/pair/2023-07-28/pair_scalability_time.csv")
colnames(df)[1] <- "Method"
data <- melt(df, id.vars="Method", variable.name="task", value.name="Runtime")
data[, "Runtime_s"] <- period_to_seconds(hms(data$Runtime))
data_melt <- data %>% mutate("Datasize" = ifelse(str_detect(task, "k"),
                                          as.integer(str_remove_all(task, "[ck]")) * 1000,
                                          as.integer(str_remove(task, "[c]"))))
## prepare palette
# mypal <- pal_d3(palette = "category20", alpha = 1)(14)
# mypal
# library(scales)
# show_col(mypal)
method_order <- c('scGen', 'inVAE', 'trVAE', 'scVIDR','scPRAM', 'biolord',
                  'scDisInFact', 'CellOT', 'SCREEN', 'scPreGAN','trainMean', "controlMean", "baseMLP", 'baseReg')
color_value <- c("scGen" = 'lightpink', "scVIDR" = '#F5B215', "biolord" = '#A4D29C',
                 "CellOT" = 'lightskyblue', "inVAE" = 'mediumpurple', "trVAE" = '#6CBB53',
                 "scPRAM" = '#E2B484', "scPreGAN" = '#C65388',
                 "SCREEN" = '#8C1C37', "scDisInFact" = 'royalblue',
                 'trainMean' = '#E73118', "controlMean" = '#BBBBFC', "baseMLP" = 'aquamarine', 'baseReg' = 'hotpink1')



## plot
p1 <- ggplot(data_melt, aes(x=Datasize, y=Runtime_s, colour=Method)) +
  geom_line() +
  geom_point() +
  # ylim(0, 100000) + # 设置y轴的范围
  scale_y_log10(breaks = c(1, 60, 3600, 86400),
                labels = c("1 s", "1 min", "1 h", "1 day"),
                expand = expansion(mult = c(0.01, 0.1)) # 使用expand参数来调整y轴的范围
                ) +
  scale_x_log10(breaks = c(500, 1000, 5000, 10000, 50000, 100000, 500000),
                labels = scales::scientific, # 使用expand参数来调整y轴的范围
                ) +
  # scale_color_brewer(palette = "Set1") + # 使用RColorBrewer包的Set1调色板
  scale_color_manual(values = mypal,
                     guide = guide_legend(override.aes = list(shape=19, size = 4, alpha = 1))) + # 使用自定义调色板; 修改图例样式
  labs(x = "Datasize (number of cells)", y = "Time") + 
  # theme(legend.text = element_text(size=12, color="red"))
  theme(legend.position = "none",  # 移除图例
        # legend.background = element_blank(),  # 移除图例背景
        # legend.key = element_blank(),         # 移除图例边框
        # legend.title = element_blank(),       # 移除图例标题
        panel.background =  element_rect(fill = "white", colour = "black"), # 白色背景和黑色边框
        panel.grid.major = element_blank(),              # 移除主要网格线
        panel.grid.minor = element_blank()               # 移除次要网格线
        ) 

p1


# pair_scalability_memory.csv
## data clean
df <- read.csv("/home/wsg/BM/assess/BMMC/scalability/pair/2023-07-28/pair_scalability_memory.csv")
colnames(df)[1] <- "Method"
data <- melt(df, id.vars="Method", variable.name="task", value.name="Max_memory")
data[, "Max_memory_MB"] <- as.numeric(gsub(",", "", data$Max_memory))/(1024)
data[, "Max_memory_GB"] <- as.numeric(gsub(",", "", data$Max_memory))/(1024^2)

data_melt <- data %>% mutate("Datasize" = ifelse(str_detect(task, "k"),
                                                 as.integer(str_remove_all(task, "[ck]")) * 1000,
                                                 as.integer(str_remove(task, "[c]"))))
## prepare palette
library(ggsci)
mypal <- pal_d3(palette = "category20", alpha = 1)(14)
mypal
library(scales)
show_col(mypal)


## plot
p2 <- ggplot(data_melt, aes(x=Datasize, y=Max_memory_GB, colour=Method)) +
  geom_line() +
  geom_point() +
  # ylim(0, 100000) + # 设置y轴的范围
  scale_y_log10(breaks = c(1, 10, 100, 1024),
                labels = c("1 GB", "10 GB", "100 GB", "1TB"),
                expand = expansion(mult = c(0.1, 0.2)) # 使用expand参数来调整y轴的范围
  ) +
  scale_x_log10(breaks = c(500, 1000, 5000, 10000, 50000, 100000, 500000),
                labels = scales::scientific, # 使用expand参数来调整y轴的范围
  ) +
  # scale_color_brewer(palette = "Set1") + # 使用RColorBrewer包的Set1调色板
  scale_color_manual(values = mypal,
                     guide = guide_legend(override.aes = list(shape=19, size = 4, alpha = 1))) + # 使用自定义调色板; 修改图例样式
  labs(x = "Datasize (number of cells)", y = "Time") + 
  # theme(legend.text = element_text(size=12, color="red"))
  theme(legend.position = "none",  # 移除图例
        # legend.background = element_blank(),  # 移除图例背景
        # legend.key = element_blank(),         # 移除图例边框
        # legend.title = element_blank(),       # 移除图例标题
        panel.background =  element_rect(fill = "white", colour = "black"), # 白色背景和黑色边框
        panel.grid.major = element_blank(),              # 移除主要网格线
        panel.grid.minor = element_blank()               # 移除次要网格线
  ) 

p2

# pair_scalability_GPU.csv
## data clean
df <- read.csv("/home/wsg/BM/assess/BMMC/scalability/pair/2023-07-28/pair_scalability_GPU.csv")
colnames(df)[1] <- "Method"
data <- melt(df, id.vars="Method", variable.name="task", value.name="Max_memory")
data[, "Max_memory_GB"] <- as.numeric(gsub("MiB", "", data$Max_memory))/(1024)

data_melt <- data %>% mutate("Datasize" = ifelse(str_detect(task, "k"),
                                                 as.integer(str_remove_all(task, "[ck]")) * 1000,
                                                 as.integer(str_remove(task, "[c]"))))
## prepare palette
library(ggsci)
mypal <- pal_d3(palette = "category20", alpha = 1)(14)
mypal
library(scales)
show_col(mypal)


## plot
p3 <- ggplot(data_melt, aes(x=Datasize, y=Max_memory_GB, colour=Method)) +
  geom_line() +
  geom_point() +
  # ylim(0, 100000) + # 设置y轴的范围
  scale_y_continuous(breaks = c(1, 5, 10, 15, 20),
                     labels = c("1 GB", "5 GB", "10 GB", "15 GB", "20 GB"),
                     # expand = expansion(mult = c(0.1, 0.2)) # 使用expand参数来调整y轴的范围
  ) +
  scale_x_log10(breaks = c(500, 1000, 5000, 10000, 50000, 100000, 500000),
                labels = scales::scientific, # 使用expand参数来调整y轴的范围
  ) +
  # scale_color_brewer(palette = "Set1") + # 使用RColorBrewer包的Set1调色板
  scale_color_manual(values = mypal,
                     guide = guide_legend(override.aes = list(shape=19, size = 4, alpha = 1))) + # 使用自定义调色板; 修改图例样式
  labs(x = "Datasize (number of cells)", y = "Time") + 
  # theme(legend.text = element_text(size=12, color="red"))
  theme(legend.background = element_blank(),  # 移除图例背景
        legend.key = element_blank(),         # 移除图例边框
        legend.title = element_blank(),       # 移除图例标题
        panel.background =  element_rect(fill = "white", colour = "black"), # 白色背景和黑色边框
        panel.grid.major = element_blank(),              # 移除主要网格线
        panel.grid.minor = element_blank()               # 移除次要网格线
  ) 

p3


# 为每个图表添加标题
p1 <- p1 + ggtitle("pair time")
p2 <- p2 + ggtitle("pair memory")
p3 <- p3 + ggtitle("pair GPU")

# 使用 plot_grid 拼接图表
combined_plot <- plot_grid(p1, p2, p3, ncol = 3)

# 显示拼接后的图表
print(combined_plot)

# 使用 plot_grid 拼接图表
combined_plot <- plot_grid(p1, p2, p3, ncol = 3, rel_widths = c(1,1,1.25))

# 显示拼接后的图表
print(combined_plot)
output_path <- "/home/wsg/BM/visualization"
save_plot(paste0(output_path, "/pair_scalability.png"), combined_plot, base_width = 18, base_height = 6)

```

